// src/lib/division.ts
export type GoverningBody = 'PMC' | 'PCMC' | 'ZP';

export type Division = {
  kramank: string;
  name: string;
  body: GoverningBody;
};

export const DIVISION_DATA: Record<GoverningBody, Omit<Division, 'body'>[]> = {
  PMC: [
    { kramank: '1', name: 'Kasba-Vishrambagwada' },
    { kramank: '2', name: 'Shivajinagar' },
    { kramank: '3', name: 'Dhole Patil Road' },
    { kramank: '4', name: 'Yerawada' },
    { kramank: '5', name: 'Kondhwa' },
    { kramank: '6', name: 'Hadapsar' },
    { kramank: '7', name: 'Kothrud' },
    { kramank: '8', name: 'Baner' },
    { kramank: '9', name: 'Aundh' },
    { kramank: '10', name: 'Balewadi' },
    { kramank: '11', name: 'Wakad' },
    { kramank: '12', name: 'Hinjewadi' },
    { kramank: '13', name: 'Mundhwa' },
    { kramank: '14', name: 'Kharadi' },
    { kramank: '15', name: 'Vadgaon Sheri' },
    { kramank: '16', name: 'Manjri' },
    { kramank: '17', name: 'Uruli Devachi' },
    { kramank: '18', name: 'Loni Kalbhor' },
    { kramank: '19', name: 'Katraj' },
    { kramank: '20', name: 'Dhankawadi' },
    { kramank: '21', name: 'Bibwewadi' },
    { kramank: '22', name: 'Pune Station' },
    { kramank: '23', name: 'Camp' },
    { kramank: '24', name: 'Swargate' },
    { kramank: '25', name: 'Sahakar Nagar' },
    { kramank: '26', name: 'Parvati' },
    { kramank: '27', name: 'Gultekdi' },
    { kramank: '28', name: 'Market Yard' },
    { kramank: '29', name: 'Deccan Gymkhana' },
    { kramank: '30', name: 'Erandwane' },
    { kramank: '31', name: 'Karve Nagar' },
    { kramank: '32', name: 'Warje' },
    { kramank: '33', name: 'Sinhgad Road' },
    { kramank: '34', name: 'Narhe' },
    { kramank: '35', name: 'Ambegaon' },
    { kramank: '36', name: 'Bhor' },
    { kramank: '37', name: 'Velhe' },
    { kramank: '38', name: 'Maval' },
    { kramank: '39', name: 'Mulshi' },
    { kramank: '40', name: 'Haveli' },
    { kramank: '41', name: 'Khed' },
  ],
  PCMC: [
    { kramank: 'A', name: 'Chinchwad Gaon' },
    { kramank: 'B', name: 'Sangvi' },
    { kramank: 'C', name: 'Pimpri Gaon' },
    { kramank: 'D', name: 'Akurdi' },
    { kramank: 'E', name: 'Bhosari Gaon' },
    { kramank: 'F', name: 'Nigdi' },
    { kramank: 'G', name: 'Thergaon' },
    { kramank: 'H', name: 'Wakad' },
    { kramank: 'I', name: 'Rahatani' },
    { kramank: 'J', name: 'Kalewadi' },
    { kramank: 'K', name: 'Ravet' },
    { kramank: 'L', name: 'Tathawade' },
    { kramank: 'M', name: 'Punawale' },
    { kramank: 'N', name: 'Kiwalekar Nagar' },
    { kramank: 'O', name: 'Nehrunagar' },
    { kramank: 'P', name: 'Bhosari' },
    { kramank: 'Q', name: 'Dapodi' },
    { kramank: 'R', name: 'Phugewadi' },
    { kramank: 'S', name: 'Kasarwadi' },
    { kramank: 'T', name: 'Dehu Road' },
    { kramank: 'U', name: 'Moshi' },
    { kramank: 'V', name: 'Chikhali' },
    { kramank: 'W', name: 'Talwade' },
    { kramank: 'X', name: 'Shivne' },
    { kramank: 'Y', name: 'Mamurdi' },
    { kramank: 'Z', name: 'Indrayani Nagar' },
  ],
  ZP: [
    { kramank: 'Haveli', name: 'Haveli' },
    { kramank: 'Mulshi', name: 'Mulshi' },
    { kramank: 'Maval', name: 'Maval' },
    { kramank: 'Bhor', name: 'Bhor' },
    { kramank: 'Velhe', name: 'Velhe' },
    { kramank: 'Khed', name: 'Khed' },
    { kramank: 'Ambegaon', name: 'Ambegaon' },
    { kramank: 'Junnar', name: 'Junnar' },
    { kramank: 'Purandar', name: 'Purandar' },
    { kramank: 'Shirur', name: 'Shirur' },
    { kramank: 'Daund', name: 'Daund' },
    { kramank: 'Indapur', name: 'Indapur' },
    { kramank: 'Baramati', name: 'Baramati' },
  ],
};

export const getDivisions = (body: GoverningBody): Division[] => 
  DIVISION_DATA[body].map(p => ({...p, body }));