/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogActivityRouteImport } from './routes/log-activity'
import { Route as DivisionRouteImport } from './routes/division'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'

const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogActivityRoute = LogActivityRouteImport.update({
  id: '/log-activity',
  path: '/log-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionRoute = DivisionRouteImport.update({
  id: '/division',
  path: '/division',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/dashboard': typeof DashboardRoute
  '/division': typeof DivisionRoute
  '/log-activity': typeof LogActivityRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/dashboard': typeof DashboardRoute
  '/division': typeof DivisionRoute
  '/log-activity': typeof LogActivityRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/dashboard': typeof DashboardRoute
  '/division': typeof DivisionRoute
  '/log-activity': typeof LogActivityRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/dashboard'
    | '/division'
    | '/log-activity'
    | '/login'
    | '/objectives'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/dashboard'
    | '/division'
    | '/log-activity'
    | '/login'
    | '/objectives'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/dashboard'
    | '/division'
    | '/log-activity'
    | '/login'
    | '/objectives'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  DashboardRoute: typeof DashboardRoute
  DivisionRoute: typeof DivisionRoute
  LogActivityRoute: typeof LogActivityRoute
  LoginRoute: typeof LoginRoute
  ObjectivesRoute: typeof ObjectivesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-activity': {
      id: '/log-activity'
      path: '/log-activity'
      fullPath: '/log-activity'
      preLoaderRoute: typeof LogActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/division': {
      id: '/division'
      path: '/division'
      fullPath: '/division'
      preLoaderRoute: typeof DivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  DashboardRoute: DashboardRoute,
  DivisionRoute: DivisionRoute,
  LogActivityRoute: LogActivityRoute,
  LoginRoute: LoginRoute,
  ObjectivesRoute: ObjectivesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
